# Permalinks
permalink:        pretty

# Setup
title:            Abhigyan Khaund
tagline:          "Google Summer of Code '18"
description:      "Blog for GSoC '18 with Zulip"
url:              https://abhigyank.github.io
baseurl:          /gsoc/

author:
  name:           'Abhigyan Khaund'

paginate:         5

# Custom vars
version:          1.0.0

contact:
  github:          https://github.com/abhigyank

github:
  repo:           https://github.com/abhigyank/gsoc
